# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'osyaberiya' do
  use_frameworks!
  pod 'TwitterKit'
  pod 'FBSDKLoginKit'
  # Pods for osyaberiya

end
